name: mRAG
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch
  - torchvision
  - pytorch-cuda=12.1
  - pip:
    - fastapi
    - uvicorn[standard]
    - pydantic
    - transformers
    - sentencepiece
    - huggingface-hub
    - qdrant-client
    - pillow
    - pandas
    - tqdm
    - matplotlib
    - networkx
    - accelerate
    - lm-format-enforcer
    - pytest